import { COLORS } from "@/style/Colors";
import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingTop: 50,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    marginTop: 4,
  },
  greetingTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 8,
  },
  greetingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
  },
  greetingText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
    letterSpacing: 0.3,
  },
  headline: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.text,
    lineHeight: 28,
    maxWidth: 220,
  },
  notifBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 18,
  },
  notifDot: {
    position: "absolute",
    top: 9,
    right: 9,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: COLORS.bg,
  },

  searchWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    height: 48,
    marginBottom: 20,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    fontFamily: "System",
  },
  searchIconWrapper: {
    // no extra style needed – icon placed inline
  },
  micBtn: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
  },

  // ─── Category Pills ───────────────────────────────────────────────
  categoryList: {
    paddingBottom: 2,
    gap: 8,
    marginBottom: 22,
  },
  categoryPillActive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
  },
  categoryPillInactive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  categoryTextActive: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.white,
  },
  categoryTextInactive: {
    fontSize: 12,
    fontWeight: "600",
    color: "#555555",
  },


  // ─── Horizontal Scroll ────────────────────────────────────────────
  horizontalList: {
    paddingBottom: 4,
    gap: 12,
    marginBottom: 24,
  },

  // ─── Featured Card (horizontal) ──────────────────────────────────
  featuredCard: {
    width: 220,
    borderRadius: 18,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  featuredCardImage: {
    width: "100%",
    height: 120,
  },
  cardBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 3,
    zIndex: 2,
  },
  cardBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.primary,
  },
  heartBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 26,
    height: 26,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  cardBody: {
    padding: 12,
  },
  cardName: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 4,
    letterSpacing: -0.1,
  },
  cardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 6,
  },
  cardMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#cccccc",
  },
  cardMetaText: {
    fontSize: 11,
    color: COLORS.textSecondary,
  },
  cardRating: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.primary,
  },
  tagRow: {
    flexDirection: "row",
    gap: 5,
    flexWrap: "wrap",
  },
  tag: {
    fontSize: 10,
    fontWeight: "700",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: COLORS.primaryLight,
    color: COLORS.primary,
    overflow: "hidden",
  },
  tagGreen: {
    fontSize: 10,
    fontWeight: "700",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: COLORS.tagGreen,
    color: COLORS.tagGreenText,
    overflow: "hidden",
  },
  tagBlue: {
    fontSize: 10,
    fontWeight: "700",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: COLORS.tagBlue,
    color: COLORS.tagBlueText,
    overflow: "hidden",
  },

  // ─── Grid Cards ───────────────────────────────────────────────────
  columnWrapper: {
    justifyContent: "space-between",
    paddingBottom: 18,
  },
  gridCard: {
    width: 160,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  gridCardImage: {
    width: "100%",
    height: 90,
  },
  gridCardBody: {
    padding: 10,
  },
  gridCardName: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 3,
    letterSpacing: -0.1,
  },
  gridCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginBottom: 5,
  },
  gridCardMetaText: {
    fontSize: 10,
    color: COLORS.textMuted,
  },
  starsText: {
    fontSize: 9,
    color: COLORS.primary,
    letterSpacing: -1,
  },
  gridTag: {
    fontSize: 9,
    fontWeight: "700",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: COLORS.primaryLight,
    color: COLORS.primary,
    alignSelf: "flex-start",
    overflow: "hidden",
  },
  gridTagGreen: {
    fontSize: 9,
    fontWeight: "700",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: COLORS.tagGreen,
    color: COLORS.tagGreenText,
    alignSelf: "flex-start",
    overflow: "hidden",
  },
  gridTagBlue: {
    fontSize: 9,
    fontWeight: "700",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 5,
    backgroundColor: COLORS.tagBlue,
    color: COLORS.tagBlueText,
    alignSelf: "flex-start",
    overflow: "hidden",
  },

  // ─── Bottom padding ───────────────────────────────────────────────
  bottomPad: {
    height: 40,
  },
});
