export interface dataSet {
  type: "favorite" | "popular" | "recommended" | "all";
  data: Restaurant[];
}

export interface Restaurant {
  id: string;
  name: string;
  image: string;
  rating: number;
  distance: string;
  price: string;
  category: string;
  deliveryTime?: string;
  isTrending?: boolean;
  tags?: string[];
}

export const dataSet: dataSet[] = [
  {
    type: "favorite",
    data: [
      {
        id: "fav-1",
        name: "Saffron Kitchen",
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400",
        rating: 4.8,
        distance: "1.2 km",
        price: "10",
        category: "Italian",
        deliveryTime: "20-30 min",
        isTrending: false,
        tags: ["Pasta", "Pizza", "Wine"],
      },
      {
        id: "fav-2",
        name: "Harbour Bites",
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
        rating: 4.6,
        distance: "2.4 km",
        price: "150",
        category: "Seafood",
        deliveryTime: "25-40 min",
        isTrending: true,
        tags: ["Seafood", "Grills", "Fine Dining"],
      },
      {
        id: "fav-3",
        name: "The Spice Route",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400",
        rating: 4.7,
        distance: "0.8 km",
        price: "100",
        category: "Indian",
        deliveryTime: "15-25 min",
        isTrending: false,
        tags: ["Curry", "Tandoor", "Vegan Options"],
      },
      {
        id: "fav-4",
        name: "Tokyo Garden",
        image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
        rating: 4.9,
        distance: "3.1 km",
        price: "300",
        category: "Japanese",
        deliveryTime: "30-45 min",
        isTrending: true,
        tags: ["Sushi", "Ramen", "Sake"],
      },
      {
        id: "fav-5",
        name: "Bella Roma",
        image: "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=400",
        rating: 4.5,
        distance: "1.7 km",
        price: "100",
        category: "Italian",
        deliveryTime: "20-35 min",
        isTrending: false,
        tags: ["Pizza", "Risotto", "Desserts"],
      },
      {
        id: "fav-6",
        name: "Green Bowl",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
        rating: 4.4,
        distance: "0.5 km",
        price: "85",
        category: "Healthy",
        deliveryTime: "10-20 min",
        isTrending: false,
        tags: ["Salads", "Smoothies", "Vegan"],
      },
      {
        id: "fav-7",
        name: "Dragon Palace",
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400",
        rating: 4.3,
        distance: "2.0 km",
        price: "45",
        category: "Chinese",
        deliveryTime: "25-35 min",
        isTrending: false,
        tags: ["Dim Sum", "Noodles", "BBQ"],
      },
      {
        id: "fav-8",
        name: "Casa Mexicana",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400",
        rating: 4.6,
        distance: "1.5 km",
        price: "75",
        category: "Mexican",
        deliveryTime: "15-30 min",
        isTrending: true,
        tags: ["Tacos", "Burritos", "Margaritas"],
      },
      {
        id: "fav-9",
        name: "The Smokehouse",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400",
        rating: 4.7,
        distance: "3.5 km",
        price: "120",
        category: "BBQ",
        deliveryTime: "35-50 min",
        isTrending: true,
        tags: ["Ribs", "Brisket", "Craft Beer"],
      },
      {
        id: "fav-10",
        name: "Le Petit Bistro",
        image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400",
        rating: 4.8,
        distance: "2.8 km",
        price: "150",
        category: "French",
        deliveryTime: "30-45 min",
        isTrending: false,
        tags: ["Croissants", "Wine", "Fine Dining"],
      },
    ],
  },
  {
    type: "popular",
    data: [
      {
        id: "pop-1",
        name: "Burger Republic",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
        rating: 4.5,
        distance: "0.9 km",
        price: "100",
        category: "American",
        deliveryTime: "15-25 min",
        isTrending: true,
        tags: ["Burgers", "Fries", "Shakes"],
      },
      {
        id: "pop-2",
        name: "Noodle House",
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
        rating: 4.4,
        distance: "1.1 km",
        price: "300",
        category: "Asian",
        deliveryTime: "15-20 min",
        isTrending: false,
        tags: ["Ramen", "Pho", "Dumplings"],
      },
      {
        id: "pop-3",
        name: "Peri Peri Grill",
        image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=400",
        rating: 4.6,
        distance: "2.2 km",
        price: "542",
        category: "Grills",
        deliveryTime: "20-30 min",
        isTrending: true,
        tags: ["Chicken", "Wraps", "Platters"],
      },
      {
        id: "pop-4",
        name: "Pizza Planet",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
        rating: 4.3,
        distance: "1.4 km",
        price: "100",
        category: "Italian",
        deliveryTime: "20-35 min",
        isTrending: false,
        tags: ["Pizza", "Calzone", "Pasta"],
      },
      {
        id: "pop-5",
        name: "Taco Fiesta",
        image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400",
        rating: 4.5,
        distance: "0.7 km",
        price: "55",
        category: "Mexican",
        deliveryTime: "10-20 min",
        isTrending: true,
        tags: ["Tacos", "Nachos", "Salsa"],
      },
      {
        id: "pop-6",
        name: "Seoul Street",
        image: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=400",
        rating: 4.7,
        distance: "2.6 km",
        price: "88",
        category: "Korean",
        deliveryTime: "25-35 min",
        isTrending: true,
        tags: ["BBQ", "Bibimbap", "Kimchi"],
      },
      {
        id: "pop-7",
        name: "Mediterranean Terrace",
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400",
        rating: 4.6,
        distance: "3.0 km",
        price: "90",
        category: "Mediterranean",
        deliveryTime: "30-45 min",
        isTrending: false,
        tags: ["Mezze", "Grills", "Seafood"],
      },
      {
        id: "pop-8",
        name: "The Waffle Lab",
        image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=400",
        rating: 4.4,
        distance: "1.3 km",
        price: "34",
        category: "Cafe",
        deliveryTime: "10-20 min",
        isTrending: false,
        tags: ["Waffles", "Coffee", "Brunch"],
      },
      {
        id: "pop-9",
        name: "Thai Orchid",
        image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400",
        rating: 4.5,
        distance: "1.8 km",
        price: "78",
        category: "Thai",
        deliveryTime: "20–30 min",
        isTrending: false,
        tags: ["Pad Thai", "Curry", "Tom Yum"],
      },
      {
        id: "pop-10",
        name: "Steakhouse 1890",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
        rating: 4.8,
        distance: "4.0 km",
        price: "76",
        category: "Steakhouse",
        deliveryTime: "40–55 min",
        isTrending: true,
        tags: ["Steak", "Wine", "Fine Dining"],
      },
    ],
  },
  {
    type: "recommended",
    data: [
      {
        id: "rec-1",
        name: "Mango Tree",
        image: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=400",
        rating: 4.7,
        distance: "1.0 km",
        price: "23",
        category: "Thai",
        deliveryTime: "20–30 min",
        isTrending: true,
        tags: ["Curry", "Mango Sticky Rice", "Tom Yum"],
      },
      {
        id: "rec-2",
        name: "Olive & Vine",
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400",
        rating: 4.6,
        distance: "2.1 km",
        price: "56",
        category: "Mediterranean",
        deliveryTime: "25–40 min",
        isTrending: false,
        tags: ["Tapas", "Wine", "Cheese Board"],
      },
      {
        id: "rec-3",
        name: "Crimson Curry",
        image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
        rating: 4.8,
        distance: "0.6 km",
        price: "34",
        category: "Indian",
        deliveryTime: "15–25 min",
        isTrending: true,
        tags: ["Biryani", "Butter Chicken", "Naan"],
      },
      {
        id: "rec-4",
        name: "Ember & Oak",
        image: "https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=400",
        rating: 4.9,
        distance: "3.3 km",
        price: "135",
        category: "Modern European",
        deliveryTime: "35–50 min",
        isTrending: true,
        tags: ["Tasting Menu", "Wine Pairing", "Seasonal"],
      },
      {
        id: "rec-5",
        name: "Lotus Dim Sum",
        image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400",
        rating: 4.5,
        distance: "1.6 km",
        price: "564",
        category: "Chinese",
        deliveryTime: "20–35 min",
        isTrending: false,
        tags: ["Dim Sum", "Congee", "Fried Rice"],
      },
    ],
  },
];


export const CATEGORIES = [
  { id: "all", label: "All", icon: "home-outline" },
  { id: "pizza", label: "Pizza", emoji: "🍕" },
  { id: "sushi", label: "Sushi", emoji: "🍣" },
  { id: "burgers", label: "Burgers", emoji: "🍔" },
  { id: "salads", label: "Salads", emoji: "🥗" },
  { id: "cafe", label: "Café", emoji: "☕" },
];
